expenses/urls.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import path, reverse_lazy
from .models import Expense, Category
from .views import ExpenseListView, CategoryListView


urlpatterns = [
    path('expense/list/',
         ExpenseListView.as_view(),
         name='expense-list'),
    path('expense/create/',
         CreateView.as_view(
             model=Expense,
             fields='__all__',
             success_url=reverse_lazy('expenses:expense-list'),
             template_name='generic_update.html'
         ),
         name='expense-create'),
    path('expense/<int:pk>/edit/',
         UpdateView.as_view(
             model=Expense,
             fields='__all__',
             success_url=reverse_lazy('expenses:expense-list'),
             template_name='generic_update.html'
         ),
         name='expense-edit'),
    path('expense/<int:pk>/delete/',
         DeleteView.as_view(
             model=Expense,
             success_url=reverse_lazy('expenses:expense-list'),
             template_name='generic_delete.html'
         ),
         name='expense-delete'),

    path('category/list/',
         CategoryListView.as_view(),
         name='category-list'),
    path('category/create/',
         CreateView.as_view(
             model=Category,
             fields='__all__',
             success_url=reverse_lazy('expenses:category-list'),
             template_name='generic_update.html'
         ),
         name='category-create'),
    path('category/<int:pk>/delete/',
         DeleteView.as_view(
             model=Category,
             success_url=reverse_lazy('expenses:category-list'),
             template_name='generic_delete.html'
         ),
         name='category-delete'),

    path('category/<int:pk>/update/',
         UpdateView.as_view(
             model=Category,
             fields='__all__',
             success_url=reverse_lazy('expenses:category-list'),
             template_name='generic_update.html'
         ),
         name='category-update'),
]

project/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(pattern_name='expenses:expense-list'),
         name='dashboard'),
    path('expenses/',
         include(('expenses.urls', 'expenses'), namespace='expenses')),
]

expenses/models.py
import datetime
from django.db import models


class Category(models.Model):
    class Meta:
        ordering = ('name',)

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'


class Expense(models.Model):
    class Meta:
        ordering = ('-date', '-pk')

    category = models.ForeignKey(Category, models.PROTECT, null=True, blank=True)

    name = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    date = models.DateField(default=datetime.date.today, db_index=True)

    def __str__(self):
        return f'{self.date} {self.name} {self.amount}'

expenses/forms.py
from django import forms

from .models import Category


class ExpenseSearchForm(forms.Form):
    name = forms.CharField(required=False)
    fromdate = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}), required=False)
    todate = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}), required=False)
    category = forms.ModelMultipleChoiceField(queryset=Category.objects.all(), required=False)
    CHOICES = (('category', 'category'), ('date', 'date'),)
    order_by = forms.ChoiceField(choices=CHOICES, required=False)
    sort_descending = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = False

expenses/views.py
from django.db.models import Sum
from django.db.models.functions import ExtractYear, ExtractMonth
from django.views.generic.list import ListView

from .forms import ExpenseSearchForm
from .models import Expense, Category
from .reports import summary_per_category


class ExpenseListView(ListView):
    model = Expense
    paginate_by = 20

    def get_context_data(self, *, object_list=None, **kwargs):
        queryset = object_list if object_list is not None else self.object_list

        form = ExpenseSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data.get('name', '').strip()
            fromdate = form.cleaned_data.get('fromdate', '')
            todate = form.cleaned_data.get('todate', '')
            category = form.cleaned_data.get('category', '')
            order_by = form.cleaned_data.get('order_by', '')
            sort_descending = form.cleaned_data.get('sort_descending', '')

            filters = {}

            if name:
                filters['name__icontains'] = name
            if fromdate and todate:
                filters['date__range'] = [fromdate, todate]
            if category:
                filters['category__in'] = category

            queryset = queryset.filter(**filters)

            if order_by:
                if sort_descending:
                    queryset = queryset.order_by(order_by).reverse()
                else:
                    queryset = queryset.order_by(order_by)

            total_amount_spent = queryset.aggregate(Sum('amount'))

            total_summary_per_year_month = queryset.annotate(year=ExtractYear('date'),
                                                             month=ExtractMonth('date')). \
                values('year', 'month').annotate(sum=Sum('amount')).order_by('year', 'month')

        return super().get_context_data(
            form=form,
            object_list=queryset,
            summary_per_category=summary_per_category(queryset),
            total_amount_spent=total_amount_spent,
            total_summary_per_year_month=total_summary_per_year_month,
            **kwargs
        )


class CategoryListView(ListView):
    model = Category
    paginate_by = 5

    def get_context_data(self, **kwargs):
        query_set = [(c, Expense.objects.filter(category=c.id).count()) for c in Category.objects.all()]
        query_set = dict(query_set)

        return super().get_context_data(
            query_set=query_set,
            **kwargs
        )

expenses/templates/expenses/category_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'expenses:category-create' %}">add</a>

<table border="1">
    <thead>
    <tr>
        <th>name</th>
        <th>actions</th>
        <th>actions</th>
    </tr>
    </thead>
    <tbody>
    {% for obj in object_list %}
    <tr>
        <td>{{obj.name}}</td>
        <td><a href="{% url 'expenses:category-delete' obj.id %}">delete</a></td>
        <td><a href="{% url 'expenses:category-update' obj.id %}">update</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<table border="1">
    <thead>
    <tr>
        <th>name</th>
        <th>expenses</th>
    </tr>
    </thead>
    <tbody>
    {% for key, value in query_set.items %}
    <tr>
        <td>{{ key }}</td>
        <td>{{ value }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

expenses/templates/expenses/expense_list.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'expenses:expense-create' %}">add</a>

<form method="get" action="">
	{{form.as_p}}
	<button type="submit">search</button>
</form>
<br>
<table border="1">
	<caption>Expenses</caption>
	<thead>
	<tr>
		<th>no.</th>
		<th>category</th>
		<th>name</th>
		<th>amount</th>
		<th>date</th>
		<th>actions</th>
	</tr>
	</thead>
	<tbody>

	{% for obj in object_list %}
	<tr>
		<td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
		<td>{{ obj.category|default:"-" }}</td>
		<td>{{ obj.name|default:"-" }}</td>
		<td>{{ obj.amount|floatformat:2 }}</td>
		<td>{{obj.date}}</td>
		<td>
			<a href="{% url 'expenses:expense-edit' obj.id %}">edit</a>
			<a href="{% url 'expenses:expense-delete' obj.id %}">delete</a>
		</td>
	</tr>
	{% empty %}
	<tr>
		<td colspan="5">no items</td>
	</tr>
	{% endfor %}
	</tbody>
</table>

{% include "_pagination.html" %}
<hr>
<table border="1">
	<caption>Summary per category</caption>
	<tr>
		{% for category, total in summary_per_category.items %}
	<tr>
		<td>{{category}}:</td>
		<td>{{total|floatformat:2}}</td>
	</tr>
	{% endfor %}
	</tr>
</table>

<table border="1">
	<caption>Total amount spent</caption>
	<tr>
		<td>Total amount spent:</td>
		<td>{{total_amount_spent.amount__sum|floatformat:2}}</td>
	</tr>
</table>

<table border="5">
	<caption>Summary per year-month</caption>
	<td>Year-month:</td>
	<td>Sum:</td>
	<tr>
		{% for total in total_summary_per_year_month %}
	<tr>
		<td>{{total.year}}-{{total.month}}</td> <td>{{total.sum|floatformat:2}}</td>
	</tr>
	{% endfor %}
	</tr>
</table>
{% endblock %}

project/templates/_pagination.html
<div class="pagination">
    <span class="pagination__nav">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block meta_title %}Expenses app{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
	<a href="{% url 'expenses:expense-list' %}">Expenses</a> | 
	<a href="{% url 'expenses:category-list' %}">Categories</a> | 
	<hr>
    {% block content %}{% endblock %}
  </body>
</html>

project/templates/generic_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">delete</button>
</form>

{% endblock %}

project/templates/generic_update.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">save</button>
</form>

{% endblock %}